on:
  push:
    paths:
      - inst/selenium/src/main/java/selenium/Main.java

name: Selenium

jobs:
  selenium:
    name: Build Jar
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
        name: Git Pull

      - uses: actions/cache@v1
        name: Maven Cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build Selenium Jar
        run: |
          cd inst/selenium
          mvn package
          cp target/selenium-1.0.0-jar-with-dependencies.jar selenium.jar
          git add selenium.jar
          git commit -m 'Maven build (GitHub Actions)' || echo "No Maven changes to commit"

      - name: Git Push
        if: github.event_name == 'push'
        run: |
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to push"
