on:
  push:
    # paths:
    #   - inst/selenium/src/main/kotlin/com/rstudio/seleniumRunner/Main.kt
    branches:
      - master
      - ghactions
  pull_request:
    branches:
      - master
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  schedule:
    - cron:  '0 0 * * 1' # every monday at midnight
  repository_dispatch:
    types:
      - all
      - selenium
      - rituals
      - build


name: Selenium

jobs:
  selenium:
    name: Build Jar
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
        if: github.event_name != 'pull_request'
        name: Git Pull
      - uses: actions/checkout@v1
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/cache@v1
        name: Maven Cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Git Config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"


      - name: Build Selenium Jar
        run: |
          cd inst/selenium
          mvn package
          cp target/selenium-1.0.0-jar-with-dependencies.jar selenium.jar
          git add selenium.jar
          git commit -m 'Maven build (GitHub Actions)' || echo "No Maven changes to commit"

      - name: Git Push (PR)
        uses: r-lib/actions/pr-push@master
        if: github.event_name != 'push'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Git Push (Branch)
        if: github.event_name == 'push'
        run: |
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to push"
