name: R CMD check
on:
  - push
jobs:
  build:
    runs-on: ubuntu-18.04
    container: "rocker/verse:latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Install devtools
        run: |-
          Rscript -e "remotes::install_cran('devtools', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: "devtools::check()"
        run: |-
          Rscript -e "devtools::check(error_on = 'note', run_dont_test = TRUE)"
