on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

name: Deploy gh-pages

jobs:
  render:
    name: "Render pkgdown"
    runs-on: ubuntu-16.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Render site
        run: |
          Rscript -e 'install.packages("pkgdown")'
          Rscript -e 'pkgdown::build_site()'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
