on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

name: Deploy gh-pages

jobs:
  # # added so that the workflow doesn't fail.
  # always_runner:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Always run
  #       run: echo "This job is used to prevent the workflow status from showing as failed when all other jobs are skipped"

  render:
    name: "Render pkgdown"
    # if: false
    runs-on: ubuntu-16.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: "https://packagemanager.rstudio.com/all/__linux__/xenial/latest"
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pak and query dependencies
        shell: Rscript {0}
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        shell: Rscript {0}
        run: |
          pak::local_system_requirements(execute = TRUE)
          pak::pkg_system_requirements("rcmdcheck", execute = TRUE)

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          pak::local_install_dev_deps(upgrade = TRUE)
          pak::local_install(upgrade = TRUE)
          pak::pkg_install("pkgdown")

      - name: Render site
        run: >
          Rscript
          -e 'pkgdown::build_site()'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
