on:
  push:
    branches:
      - master
      - ghactions
  pull_request:
    branches:
      - master
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  schedule:
    - cron:  '0 0 * * 1' # every monday at midnight

name: Headless Browser

jobs:

  headless:
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest, r: '3.6'}
        - { os: ubuntu-16.04, r: '3.6', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
    runs-on: ${{ matrix.config.os }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1

      - name: Setup macOS Browsers
        if: runner.os == 'macOS'
        run: |
          brew update
          brew cask install google-chrome
          brew cask info google-chrome
          brew cask install firefox
          brew cask info firefox
      - name: Setup Linux Browsers
        if: runner.os == 'Linux'
        run: |
          which google-chrome
          which firefox

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ github.ref }}
          restore_keys: |
            ${{ runner.os }}-r-${{ matrix.config.r }}-${{ github.ref }}
            ${{ runner.os }}-r-${{ matrix.config.r }}-${{ github.base_ref }}

      - name: Install remotes
        run: >
          Rscript
          -e "if (system.file(package = 'remotes') == '') install.packages('remotes')"
          -e "remotes::install_github('r-hub/sysreqs')"

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install shinyjster
        run: >
          Rscript
          -e "remotes::install_deps(dependencies = TRUE)"
          -e "remotes::install_local(dependencies = TRUE, force = TRUE)"
      - name: Add shinyjster matchers
        run: echo "::add-matcher::.github/matchers/shinyjster.json"

      - name: Install app deps
        run: >
          Rscript
          -e "remotes::install_cran('renv')"
          -e 'lapply(print(unique(renv::dependencies(system.file("shinyjster", package = "shinyjster"), quiet = TRUE)$Package)), remotes::install_cran)'
      # to avoid odd 'raw' bug
      - name: Install rstudio/shiny
        if: runner.os == 'Linux'
        run: >
          Rscript
          -e "remotes::install_github('rstudio/shiny')"

      - name: Run headless Chrome checks
        run: >
          Rscript
          -e "shinyjster::run_headless(browser = 'chrome', type = 'lapply')"
      - name: Run headless Firefox checks
        if: false
        run: >
          Rscript
          -e "shinyjster::run_headless(browser = 'firefox', type = 'lapply')"
