name: CICD
on:
  - push
jobs:

  "mac-r-cmd-check":
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Install brew
        run: |-
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Install R
        run: |-
          brew install r
      - name: R Options
        run: |-
          echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > ~/.Rprofile.site
      - name: Cache R library
        uses: actions/cache@v1
        with:
          path: "/Library/Frameworks/R.framework/Resources/library"
          key: ${{ runner.OS }}-library-${{ hashFiles('**/DESCRIPTION') }}
      - name: Install Package Dependencies
        run: |-
          Rscript -e "if(!requireNamespace('remotes', quietly = TRUE)) {install.packages('remotes', repos = Sys.getenv('CRAN_REPO'))}"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = Sys.getenv('CRAN_REPO'))"
          Rscript -e "remotes::install_cran('devtools', repos = Sys.getenv('CRAN_REPO'))"
      - name: "devtools::check()"
        run: |-
          Rscript -e "devtools::check(error_on = 'note', run_dont_test = TRUE, cran = TRUE, remote = TRUE, manual = TRUE)"

  "r-cmd-check":
    # if: false
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        container:
          # - "rocker/r-ver:3.5.3"
          # - "rocker/verse:latest"
          - "rocker/verse:devel"
      fail-fast: true
    container: ${{ matrix.container }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: R Options
        run: |-
          echo 'options(repos = c(CRAN = "https://demo.rstudiopm.com/all/__linux__/bionic/latest"))' > ~/.Rprofile.site
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = Sys.getenv('CRAN_REPO'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = Sys.getenv('CRAN_REPO'))"
          Rscript -e "remotes::install_cran('devtools', repos = Sys.getenv('CRAN_REPO'))"
      - name: "devtools::check()"
        run: |-
          Rscript -e "devtools::check(error_on = 'note', run_dont_test = TRUE, cran = TRUE, remote = TRUE, manual = TRUE)"

  "pkgdown":
    if: false
    runs-on: ubuntu-18.04
    container: "rocker/verse:latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: R Options
        run: |-
          echo 'options(repos = c(CRAN = "https://demo.rstudiopm.com/all/__linux__/bionic/latest"))' > ~/.Rprofile.site
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = Sys.getenv('CRAN_REPO'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = Sys.getenv('CRAN_REPO'))"
      - name: Render Site
        run: |-
          Rscript -e "remotes::install_cran('pkgdown')"
          Rscript -e "pkgdown::build_site()"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
