name: CICD
on:
  - push
jobs:

  "check-devel":
    runs-on: ubuntu-18.04
    container: "rocker/verse:devel"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Install devtools
        run: |-
          Rscript -e "remotes::install_cran('devtools', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: "devtools::check()"
        run: |-
          Rscript -e "devtools::check(error_on = 'note', run_dont_test = TRUE)"

  "check-release":
    runs-on: ubuntu-18.04
    container: "rocker/verse:latest"
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Install devtools
        run: |-
          Rscript -e "remotes::install_cran('devtools', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: "devtools::check()"
        run: |-
          Rscript -e "devtools::check(error_on = 'note', run_dont_test = TRUE)"


  "pkgdown":
    runs-on: ubuntu-18.04
    container: "rocker/verse:latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Render Site
        run: |-
          Rscript -e "remotes::install_cran('pkgdown')"
          Rscript -e "pkgdown::build_site()"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
