# Workflow derived from https://github.com/rstudio/shiny-workflows
#
# NOTE: This Shiny team GHA workflow is overkill for most R packages.
# For most R packages it is better to use https://github.com/r-lib/actions
on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 8 * * 1' # every monday

name: Package checks

jobs:
  website:
    uses: rstudio/shiny-workflows/.github/workflows/website.yaml@v1
  routine:
    uses: rstudio/shiny-workflows/.github/workflows/routine.yaml@v1
    with:
      node-version: "14.x"
  R-CMD-check:
    uses: rstudio/shiny-workflows/.github/workflows/R-CMD-check.yaml@v1

  headless:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: 'release'}
        - { os: macOS-latest, r: 'release'}
        - { os: ubuntu-18.04, r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          extra-packages: |
            future
            promises
            magrittr
            ggplot2

      - name: Headless Check (Setup)
        shell: Rscript {0}
        run: |
          pak::local_install()
      - name: Headless Check
        timeout-minutes: 45
        shell: Rscript {0}
        env:
          # firefox needs creds to download drivers?
          # https://github.com/bonigarcia/webdrivermanager#http-response-code-403
          WDM_GITHUBTOKENNAME: ${{ github.actor }}
          WDM_GITHUBTOKENSECRET: ${{ secrets.GITHUB_TOKEN }}
        run: |
          shinyjster:::test_jster_internal()
